"""Generation Models

Revision ID: 85067581bdbd
Revises: 938383c31205
Create Date: 2025-01-30 10:13:10.992274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85067581bdbd"
down_revision: Union[str, None] = "938383c31205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_generations_model_id_gen_models"),
            "gen_models",
            ["model_id"],
            ["id"],
        )
        batch_op.drop_column("endpoint")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("endpoint", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_generations_model_id_gen_models"), type_="foreignkey"
        )
        batch_op.drop_column("model_id")

    # ### end Alembic commands ###
